site_name: 產品手冊與計算工具 | Product Manual
theme:
  name: material
  palette:
    primary: blue grey # 您可以改顏色，例如 indigo, red, green
  language: zh-TW      # 預設介面語言
  features:
    - navigation.tabs  # 啟用上方頁籤

# 這裡設定雙語切換按鈕
extra:
  alternate:
    - name: 繁體中文
      link: /zh/
      lang: zh-TW
    - name: English
      link: /en/
      lang: en

# 這裡設定左側目錄
nav:
  - 繁體中文:
    - 首頁: zh/index.md
  - English:
    - Home: en/index.md
