site_name: 產品手冊與計算工具 | Product Manual
site_url: https://hephas.github.io/hephas_manual/

theme:
  name: material
  palette:
    primary: blue grey
  language: zh-TW
  features:
    - navigation.tabs

# 雙語切換按鈕 (加上了完整子目錄路徑)
extra:
  alternate:
    - name: 繁體中文
      link: /hephas_manual/zh/
      lang: zh-TW
    - name: English
      link: /hephas_manual/en/
      lang: en

# 左側目錄結構
nav:
  - 選擇語言 Language: index.md
  - 繁體中文:
    - 首頁: zh/index.md
    - 一般說明: zh/general.md
  - English:
    - Home: en/index.md
    
# 載入自訂的翻譯腳本
extra_javascript:
  - javascripts/translate.js
